import des from '../images/n.jpg';
import ds from '../images/che.jpg';
import ahm from '../images/ahmed.jpg';
import wiz from '../images/mac.jpg';
import desk from '../images/Desktop - 4.jpg';
import dsk from '../images/Desktop - 1.jpg';

const data = [
  {
    id: 1,
    image: des,
    profiile: ahm,
    name: 'Tossmax',
    decr: 'Brand Identity De...',
    like: 444,
    view: 1499,
    Pro: false,
  },
  {
    id: 2,
    image: wiz,
    profiile: ahm,
    name: 'Tossmax',
    decr: 'Website Applica...',
    like: 242,
    view: 1888,
    Pro: false,
  },
  {
    id: 3,
    image: ds,
    profiile: ahm,
    name: 'Tossmax',
    decr: 'Brand Identity De...',
    like: 66,
    view: 765,
    Pro: true,
  },
  {
    id: 4,
    image: desk,
    profiile: ahm,
    name: 'Tossmax',
    decr: 'Mobile Application',
    like: 775,
    view: 675,
    Pro: false,
  },
  {
    id: 5,
    image: dsk,
    profiile: ahm,
    name: 'Tossmax',
    decr: 'Mobile Application',
    like: 111,
    view: 435,
    Pro: false,
  },
  {
    id: 6,
    image: ds,
    profiile: ahm,
    name: 'Tossmax',
    decr: 'Mobile Application',
    like: 352,
    view: 899,
    Pro: true,
  },
  {
    id: 7,
    image: wiz,
    profiile: ahm,
    name: 'Tossmax',
    decr: 'Mobile Application',
    like: 534,
    view: 2199,
    Pro: false,
  },
  {
    id: 8,
    image: dsk,
    profiile: ahm,
    name: 'Tossmax',
    decr: 'Mobile Application',
    like: 343,
    view: 180,
    Pro: false,
  },
  {
    id: 9,
    image: des,
    profiile: ahm,
    name: 'Tossmax',
    decr: 'Mobile Application',
    like: 55,
    view: 70,
    Pro: true,
  },
  {
    id: 10,
    image: desk,
    profiile: ahm,
    name: 'Tossmax',
    decr: 'Mobile Application',
    like: 77,
    view: 1999,
    Pro: false,
  },
  {
    id: 11,
    image: des,
    profiile: ahm,
    name: 'Tossmax',
    decr: 'Mobile Application',
    like: 872,
    view: 679,
    Pro: false,
  },
  {
    id: 12,
    image: wiz,
    profiile: ahm,
    name: 'Tossmax',
    decr: 'Mobile Application',
    like: 354,
    view: 111,
    Pro: true,
  },
  {
    id: 13,
    image: desk,
    profiile: ahm,
    name: 'Tossmax',
    decr: 'Mobile Application',
    like: 443,
    view: 900,
    Pro: false,
  },
  {
    id: 14,
    image: wiz,
    profiile: ahm,
    name: 'Tossmax',
    decr: 'Mobile Application',
    like: 999,
    view: 1800,
    Pro: false,
  },
  {
    id: 15,
    image: dsk,
    profiile: ahm,
    name: 'Tossmax',
    decr: 'Mobile Application',
    like: 400,
    view: 345,
    Pro: true,
  },
  {
    id: 16,
    image: ds,
    profiile: ahm,
    name: 'Tossmax',
    decr: 'Mobile Application',
    like: 998,
    view: 70,
    Pro: true,
  },
];

export default data;
